[package]
name = "gurupia-parser"
version = "0.2.0"
edition = "2021"
rust-version = "1.80"

[dependencies]
quick-xml = "0.36"
regex = "1.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
